/* Generated by Cython 0.24.1 */

#ifndef __PYX_HAVE___simple_physics
#define __PYX_HAVE___simple_physics


#ifndef __PYX_HAVE_API___simple_physics

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *init_arrays(int, int, double, int);
__PYX_EXTERN_C DL_IMPORT(PyObject) *get_tendencies(PyArrayObject *, PyArrayObject *, PyArrayObject *, PyArrayObject *, PyArrayObject *, PyArrayObject *, PyArrayObject *, PyArrayObject *);

#endif /* !__PYX_HAVE_API___simple_physics */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_simple_physics(void);
#else
PyMODINIT_FUNC PyInit__simple_physics(void);
#endif

#endif /* !__PYX_HAVE___simple_physics */
